// Shared mock data for Storybook. Never used by the app itself.
import type { Artist } from "../types/entities";
import type { MapShopData } from "../components/map/MapShopPanel";

export const mockArtists: Artist[] = [
  {
    id: 1,
    name: "Sailor Jerry",
    slug: "sailor-jerry",
    instagram_handle: "sailorjerry",
    is_traveling: false,
    city_name: "Honolulu",
    state_name: "Hawaii",
    country_name: "United States",
    shop_id: 10,
    shop_name: "Old Ironside Tattoo",
    shop_slug: "old-ironside-tattoo",
    shop_instagram_handle: "oldironsidetattoo",
    locations: [
      {
        city_name: "Honolulu",
        state_name: "Hawaii",
        country_name: "United States",
        shop_id: 10,
        shop_name: "Old Ironside Tattoo",
        shop_slug: "old-ironside-tattoo",
        shop_instagram_handle: "oldironsidetattoo",
        is_primary: true,
      },
    ],
  },
  {
    id: 2,
    name: "Ed Hardy",
    slug: "ed-hardy",
    instagram_handle: "edhardy",
    is_traveling: false,
    city_name: "Honolulu",
    state_name: "Hawaii",
    country_name: "United States",
    shop_id: 10,
    shop_name: "Old Ironside Tattoo",
    shop_slug: "old-ironside-tattoo",
    shop_instagram_handle: "oldironsidetattoo",
    locations: [
      {
        city_name: "Honolulu",
        state_name: "Hawaii",
        country_name: "United States",
        shop_id: 10,
        shop_name: "Old Ironside Tattoo",
        shop_slug: "old-ironside-tattoo",
        shop_instagram_handle: "oldironsidetattoo",
        is_primary: true,
      },
    ],
  },
  {
    id: 3,
    name: "Bert Grimm",
    slug: "bert-grimm",
    instagram_handle: null,
    is_traveling: false,
    city_name: "Long Beach",
    state_name: "California",
    country_name: "United States",
    shop_id: 11,
    shop_name: "Bert Grimm's World Famous Tattoo",
    shop_slug: "bert-grimm-tattoo",
    shop_instagram_handle: null,
    locations: [
      {
        city_name: "Long Beach",
        state_name: "California",
        country_name: "United States",
        shop_id: 11,
        shop_name: "Bert Grimm's World Famous Tattoo",
        shop_slug: "bert-grimm-tattoo",
        shop_instagram_handle: null,
        is_primary: true,
      },
    ],
  },
  {
    id: 4,
    name: "Kari Barba",
    slug: "kari-barba",
    instagram_handle: "karibarba",
    is_traveling: true,
    city_name: "Anaheim",
    state_name: "California",
    country_name: "United States",
    shop_id: 12,
    shop_name: "Outer Limits Tattoo",
    shop_slug: "outer-limits-tattoo",
    shop_instagram_handle: "outerlimitstattoo",
    locations: [
      {
        city_name: "Anaheim",
        state_name: "California",
        country_name: "United States",
        shop_id: 12,
        shop_name: "Outer Limits Tattoo",
        shop_slug: "outer-limits-tattoo",
        shop_instagram_handle: "outerlimitstattoo",
        is_primary: true,
      },
      {
        city_name: "Long Beach",
        state_name: "California",
        country_name: "United States",
        shop_id: 13,
        shop_name: "Long Beach Tattoo",
        shop_slug: "long-beach-tattoo",
        shop_instagram_handle: "longbeachtattoo",
        is_primary: false,
      },
    ],
  },
];

export const mockShop: MapShopData = {
  id: 10,
  shop_name: "Old Ironside Tattoo",
  slug: "old-ironside-tattoo",
  instagram_handle: "oldironsidetattoo",
  city_name: "Honolulu",
  state_name: "Hawaii",
  country_name: "United States",
  address: "1033 Smith St, Honolulu, HI 96817",
  artists: mockArtists.slice(0, 3),
};

export const mockShopEntries = [
  { id: 10, shop_name: "Old Ironside Tattoo", slug: "old-ironside-tattoo" },
  { id: 11, shop_name: "Bert Grimm's World Famous Tattoo", slug: "bert-grimm-tattoo" },
  { id: 12, shop_name: "Outer Limits Tattoo", slug: "outer-limits-tattoo" },
];
