-- saved_shops: per-user favorites for tattoo shops.
--
-- Mirrors public.saved_artists (per-user rows, RLS restricting each user to
-- their own rows, UNIQUE(user_id, entity_id), matching indexes). Difference:
-- an FK on shop_id -> tattoo_shops(id) ON DELETE CASCADE so a removed shop
-- cleans up its saved rows (saved_artists predates this and lacks the artist
-- FK; not backfilling that here). Additive/expand-only — nothing reads or
-- rewrites existing rows.

create table if not exists "public"."saved_shops" (
    "id" bigint generated by default as identity not null,
    "user_id" "uuid" not null,
    "shop_id" bigint not null,
    "created_at" timestamp with time zone default "now"() not null
);

alter table "public"."saved_shops" enable row level security;

alter table only "public"."saved_shops"
    add constraint "saved_shops_pkey" primary key ("id");

alter table only "public"."saved_shops"
    add constraint "saved_shops_user_id_shop_id_key" unique ("user_id", "shop_id");

alter table only "public"."saved_shops"
    add constraint "saved_shops_user_id_fkey" foreign key ("user_id")
    references "auth"."users"("id") on delete cascade;

alter table only "public"."saved_shops"
    add constraint "saved_shops_shop_id_fkey" foreign key ("shop_id")
    references "public"."tattoo_shops"("id") on delete cascade;

create index "idx_saved_shops_user_id" on "public"."saved_shops" using "btree" ("user_id");
create index "idx_saved_shops_shop_id" on "public"."saved_shops" using "btree" ("shop_id");

create policy "Users can view own saved shops"
    on "public"."saved_shops" for select
    using (("auth"."uid"() = "user_id"));

create policy "Users can insert own saved shops"
    on "public"."saved_shops" for insert
    with check (("auth"."uid"() = "user_id"));

create policy "Users can delete own saved shops"
    on "public"."saved_shops" for delete
    using (("auth"."uid"() = "user_id"));

grant all on table "public"."saved_shops" to "anon";
grant all on table "public"."saved_shops" to "authenticated";
grant all on table "public"."saved_shops" to "service_role";
